# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 03:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('shorten_hash', models.CharField(blank=True, max_length=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BitlinkLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_referer', models.CharField(blank=True, max_length=255, null=True)),
                ('http_user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('http_remote_address', models.CharField(blank=True, max_length=31, null=True)),
                ('http_meta_json', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bitlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitly.Bitlink')),
            ],
        ),
    ]
